// src/data/transactions.ts

export type TransactionType = "income" | "expense";

export type Transaction = {
  id: string;
  title: string;
  category: string;
  type: TransactionType;
  amount: number;
  date: string;
  paymentMethod: string;
  note?: string;
};

export const transactions: Transaction[] = [
 
  {
    id: "1",
    title: "Monthly Salary",
    category: "Salary",
    type: "income",
    amount: 4200,
    date: "2026-04-01",
    paymentMethod: "Bank Transfer",
    note: "April salary",
  },
  {
    id: "2",
    title: "Grocery Store",
    category: "Food",
    type: "expense",
    amount: 84,
    date: "2026-04-03",
    paymentMethod: "Card",
  },
  {
    id: "3",
    title: "Uber Ride",
    category: "Transport",
    type: "expense",
    amount: 22,
    date: "2026-04-04",
    paymentMethod: "Card",
  },
  {
    id: "4",
    title: "Coffee Shop",
    category: "Food",
    type: "expense",
    amount: 14,
    date: "2026-04-05",
    paymentMethod: "Cash",
  },
  {
    id: "5",
    title: "Internet Bill",
    category: "Utilities",
    type: "expense",
    amount: 60,
    date: "2026-04-05",
    paymentMethod: "UPI",
  },
  {
    id: "6",
    title: "Freelance Project",
    category: "Freelance",
    type: "income",
    amount: 950,
    date: "2026-04-06",
    paymentMethod: "UPI",
    note: "Logo design",
  },

  // ── MARCH 2026 ──────────────────────────────────────────────────────────────
  {
    id: "7",
    title: "Monthly Salary",
    category: "Salary",
    type: "income",
    amount: 4200,
    date: "2026-03-01",
    paymentMethod: "Bank Transfer",
    note: "March salary",
  },
  {
    id: "8",
    title: "Gaming Steam",
    category: "Entertainment",
    type: "expense",
    amount: 35,
    date: "2026-03-01",
    paymentMethod: "Card",
    note: "Steam game sale",
  },
  {
    id: "9",
    title: "Water Bill",
    category: "Utilities",
    type: "expense",
    amount: 20,
    date: "2026-03-02",
    paymentMethod: "UPI",
  },
  {
    id: "10",
    title: "Clothes Shopping",
    category: "Shopping",
    type: "expense",
    amount: 110,
    date: "2026-03-03",
    paymentMethod: "Card",
  },
  {
    id: "11",
    title: "Lunch",
    category: "Food",
    type: "expense",
    amount: 14,
    date: "2026-03-04",
    paymentMethod: "Cash",
  },
  {
    id: "12",
    title: "Online Course",
    category: "Education",
    type: "expense",
    amount: 99,
    date: "2026-03-05",
    paymentMethod: "Card",
    note: "React advanced course",
  },
  {
    id: "13",
    title: "Medicine",
    category: "Health",
    type: "expense",
    amount: 22,
    date: "2026-03-06",
    paymentMethod: "Cash",
  },
  {
    id: "14",
    title: "Bus Pass",
    category: "Transport",
    type: "expense",
    amount: 30,
    date: "2026-03-07",
    paymentMethod: "Card",
  },
  {
    id: "15",
    title: "Books",
    category: "Education",
    type: "expense",
    amount: 45,
    date: "2026-03-08",
    paymentMethod: "Card",
  },
  {
    id: "16",
    title: "Bakery",
    category: "Food",
    type: "expense",
    amount: 16,
    date: "2026-03-09",
    paymentMethod: "Cash",
  },
  {
    id: "17",
    title: "Movie Tickets",
    category: "Entertainment",
    type: "expense",
    amount: 28,
    date: "2026-03-10",
    paymentMethod: "Card",
    note: "2 tickets",
  },
  {
    id: "18",
    title: "Mobile Recharge",
    category: "Utilities",
    type: "expense",
    amount: 25,
    date: "2026-03-11",
    paymentMethod: "UPI",
  },
  {
    id: "19",
    title: "New Shoes",
    category: "Shopping",
    type: "expense",
    amount: 89,
    date: "2026-03-12",
    paymentMethod: "Card",
  },
  {
    id: "20",
    title: "Doctor Visit",
    category: "Health",
    type: "expense",
    amount: 75,
    date: "2026-03-14",
    paymentMethod: "Cash",
  },
  {
    id: "21",
    title: "Coffee Shop",
    category: "Food",
    type: "expense",
    amount: 12,
    date: "2026-03-16",
    paymentMethod: "Card",
  },
  {
    id: "22",
    title: "Electricity Bill",
    category: "Utilities",
    type: "expense",
    amount: 120,
    date: "2026-03-17",
    paymentMethod: "UPI",
    note: "March bill",
  },
  {
    id: "23",
    title: "Gym Membership",
    category: "Health",
    type: "expense",
    amount: 40,
    date: "2026-03-18",
    paymentMethod: "Card",
  },
  {
    id: "24",
    title: "Restaurant Dinner",
    category: "Food",
    type: "expense",
    amount: 42,
    date: "2026-03-20",
    paymentMethod: "Card",
    note: "Dinner with friends",
  },
  {
    id: "25",
    title: "Bonus",
    category: "Salary",
    type: "income",
    amount: 1500,
    date: "2026-03-20",
    paymentMethod: "Bank Transfer",
    note: "Q1 performance bonus",
  },
  {
    id: "26",
    title: "Netflix",
    category: "Entertainment",
    type: "expense",
    amount: 15,
    date: "2026-03-20",
    paymentMethod: "Card",
  },
  {
    id: "27",
    title: "Amazon Order",
    category: "Shopping",
    type: "expense",
    amount: 134,
    date: "2026-03-22",
    paymentMethod: "Card",
    note: "Keyboard + mousepad",
  },
  {
    id: "28",
    title: "Fuel",
    category: "Transport",
    type: "expense",
    amount: 55,
    date: "2026-03-24",
    paymentMethod: "Cash",
  },
  {
    id: "29",
    title: "Stock Dividend",
    category: "Investment",
    type: "income",
    amount: 340,
    date: "2026-03-25",
    paymentMethod: "Bank Transfer",
  },
  {
    id: "30",
    title: "Spotify Premium",
    category: "Entertainment",
    type: "expense",
    amount: 10,
    date: "2026-03-28",
    paymentMethod: "Card",
  },
  {
    id: "31",
    title: "Freelance Project",
    category: "Freelance",
    type: "income",
    amount: 800,
    date: "2026-03-28",
    paymentMethod: "UPI",
  },
  {
    id: "32",
    title: "Selling Old Laptop",
    category: "Other",
    type: "income",
    amount: 280,
    date: "2026-03-30",
    paymentMethod: "Cash",
  },

  // ── FEBRUARY 2026 ───────────────────────────────────────────────────────────
  {
    id: "33",
    title: "Monthly Salary",
    category: "Salary",
    type: "income",
    amount: 4200,
    date: "2026-02-01",
    paymentMethod: "Bank Transfer",
    note: "February salary",
  },
  {
    id: "34",
    title: "Parking Fee",
    category: "Transport",
    type: "expense",
    amount: 8,
    date: "2026-02-02",
    paymentMethod: "Cash",
  },
  {
    id: "35",
    title: "Grocery Store",
    category: "Food",
    type: "expense",
    amount: 91,
    date: "2026-02-04",
    paymentMethod: "Card",
  },
  {
    id: "36",
    title: "Electricity Bill",
    category: "Utilities",
    type: "expense",
    amount: 115,
    date: "2026-02-06",
    paymentMethod: "UPI",
    note: "February bill",
  },
  {
    id: "37",
    title: "Valentine Dinner",
    category: "Food",
    type: "expense",
    amount: 68,
    date: "2026-02-14",
    paymentMethod: "Card",
    note: "Valentine's day",
  },
  {
    id: "38",
    title: "Gym Membership",
    category: "Health",
    type: "expense",
    amount: 40,
    date: "2026-02-15",
    paymentMethod: "Card",
  },
  {
    id: "39",
    title: "Mobile Recharge",
    category: "Utilities",
    type: "expense",
    amount: 25,
    date: "2026-02-16",
    paymentMethod: "UPI",
  },
  {
    id: "40",
    title: "Amazon Order",
    category: "Shopping",
    type: "expense",
    amount: 76,
    date: "2026-02-18",
    paymentMethod: "Card",
    note: "Home essentials",
  },
  {
    id: "41",
    title: "Freelance Project",
    category: "Freelance",
    type: "income",
    amount: 600,
    date: "2026-02-20",
    paymentMethod: "UPI",
  },
  {
    id: "42",
    title: "Fuel",
    category: "Transport",
    type: "expense",
    amount: 50,
    date: "2026-02-22",
    paymentMethod: "Cash",
  },
  {
    id: "43",
    title: "Netflix",
    category: "Entertainment",
    type: "expense",
    amount: 15,
    date: "2026-02-22",
    paymentMethod: "Card",
  },
  {
    id: "44",
    title: "Spotify Premium",
    category: "Entertainment",
    type: "expense",
    amount: 10,
    date: "2026-02-25",
    paymentMethod: "Card",
  },
  {
    id: "45",
    title: "Medicine",
    category: "Health",
    type: "expense",
    amount: 30,
    date: "2026-02-26",
    paymentMethod: "Cash",
  },
  {
    id: "46",
    title: "Books",
    category: "Education",
    type: "expense",
    amount: 38,
    date: "2026-02-27",
    paymentMethod: "Card",
  },

  // ── JANUARY 2026 ────────────────────────────────────────────────────────────
  {
    id: "47",
    title: "Monthly Salary",
    category: "Salary",
    type: "income",
    amount: 4200,
    date: "2026-01-01",
    paymentMethod: "Bank Transfer",
    note: "January salary",
  },
  {
    id: "48",
    title: "New Year Dinner",
    category: "Food",
    type: "expense",
    amount: 95,
    date: "2026-01-01",
    paymentMethod: "Card",
    note: "New year celebration",
  },
  {
    id: "49",
    title: "Grocery Store",
    category: "Food",
    type: "expense",
    amount: 78,
    date: "2026-01-05",
    paymentMethod: "Card",
  },
  {
    id: "50",
    title: "Internet Bill",
    category: "Utilities",
    type: "expense",
    amount: 60,
    date: "2026-01-07",
    paymentMethod: "UPI",
  },
  {
    id: "51",
    title: "Gym Membership",
    category: "Health",
    type: "expense",
    amount: 40,
    date: "2026-01-08",
    paymentMethod: "Card",
    note: "New year resolution",
  },
  {
    id: "52",
    title: "Online Course",
    category: "Education",
    type: "expense",
    amount: 149,
    date: "2026-01-10",
    paymentMethod: "Card",
    note: "TypeScript course",
  },
  {
    id: "53",
    title: "Clothes Shopping",
    category: "Shopping",
    type: "expense",
    amount: 145,
    date: "2026-01-12",
    paymentMethod: "Card",
    note: "Winter sale",
  },
  {
    id: "54",
    title: "Electricity Bill",
    category: "Utilities",
    type: "expense",
    amount: 130,
    date: "2026-01-14",
    paymentMethod: "UPI",
  },
  {
    id: "55",
    title: "Restaurant Lunch",
    category: "Food",
    type: "expense",
    amount: 35,
    date: "2026-01-16",
    paymentMethod: "Card",
  },
  {
    id: "56",
    title: "Fuel",
    category: "Transport",
    type: "expense",
    amount: 55,
    date: "2026-01-18",
    paymentMethod: "Cash",
  },
  {
    id: "57",
    title: "Stock Dividend",
    category: "Investment",
    type: "income",
    amount: 290,
    date: "2026-01-20",
    paymentMethod: "Bank Transfer",
  },
  {
    id: "58",
    title: "Doctor Visit",
    category: "Health",
    type: "expense",
    amount: 60,
    date: "2026-01-22",
    paymentMethod: "Cash",
  },
  {
    id: "59",
    title: "Movie Tickets",
    category: "Entertainment",
    type: "expense",
    amount: 24,
    date: "2026-01-24",
    paymentMethod: "Card",
  },
  {
    id: "60",
    title: "Mobile Recharge",
    category: "Utilities",
    type: "expense",
    amount: 25,
    date: "2026-01-26",
    paymentMethod: "UPI",
  },
  {
    id: "61",
    title: "Amazon Order",
    category: "Shopping",
    type: "expense",
    amount: 58,
    date: "2026-01-28",
    paymentMethod: "Card",
  },
  {
    id: "62",
    title: "Freelance Project",
    category: "Freelance",
    type: "income",
    amount: 700,
    date: "2026-01-30",
    paymentMethod: "UPI",
    note: "Website landing page",
  },
  // ── APRIL 2026 (additional) ─────────────────────────────────────────────────
  {
    id: "63",
    title: "Gym Membership",
    category: "Health",
    type: "expense",
    amount: 40,
    date: "2026-04-02",
    paymentMethod: "Card",
  },
  {
    id: "64",
    title: "Spotify Premium",
    category: "Entertainment",
    type: "expense",
    amount: 10,
    date: "2026-04-02",
    paymentMethod: "Card",
  },
  {
    id: "65",
    title: "Medicine",
    category: "Health",
    type: "expense",
    amount: 18,
    date: "2026-04-04",
    paymentMethod: "Cash",
  },
  {
    id: "66",
    title: "Netflix",
    category: "Entertainment",
    type: "expense",
    amount: 15,
    date: "2026-04-05",
    paymentMethod: "Card",
  },
  {
    id: "67",
    title: "Bus Pass",
    category: "Transport",
    type: "expense",
    amount: 30,
    date: "2026-04-06",
    paymentMethod: "Card",
  },

  // ── MARCH 2026 (additional) ─────────────────────────────────────────────────
  {
    id: "68",
    title: "Parking Fee",
    category: "Transport",
    type: "expense",
    amount: 10,
    date: "2026-03-02",
    paymentMethod: "Cash",
  },
  {
    id: "69",
    title: "Breakfast Cafe",
    category: "Food",
    type: "expense",
    amount: 18,
    date: "2026-03-04",
    paymentMethod: "Card",
  },
  {
    id: "70",
    title: "Vitamin Supplements",
    category: "Health",
    type: "expense",
    amount: 32,
    date: "2026-03-06",
    paymentMethod: "Card",
  },
  {
    id: "71",
    title: "Stationery",
    category: "Shopping",
    type: "expense",
    amount: 24,
    date: "2026-03-08",
    paymentMethod: "Cash",
  },
  {
    id: "72",
    title: "Investment Return",
    category: "Investment",
    type: "income",
    amount: 520,
    date: "2026-03-10",
    paymentMethod: "Bank Transfer",
    note: "Mutual fund",
  },
  {
    id: "73",
    title: "Haircut",
    category: "Other",
    type: "expense",
    amount: 15,
    date: "2026-03-13",
    paymentMethod: "Cash",
  },
  {
    id: "74",
    title: "Dinner Takeaway",
    category: "Food",
    type: "expense",
    amount: 28,
    date: "2026-03-15",
    paymentMethod: "UPI",
  },
  {
    id: "75",
    title: "Headphones",
    category: "Shopping",
    type: "expense",
    amount: 180,
    date: "2026-03-17",
    paymentMethod: "Card",
    note: "Sony WH-1000XM5",
  },
  {
    id: "76",
    title: "Yoga Class",
    category: "Health",
    type: "expense",
    amount: 25,
    date: "2026-03-19",
    paymentMethod: "UPI",
  },
  {
    id: "77",
    title: "Cab Ride",
    category: "Transport",
    type: "expense",
    amount: 20,
    date: "2026-03-21",
    paymentMethod: "Card",
  },
  {
    id: "78",
    title: "Snacks",
    category: "Food",
    type: "expense",
    amount: 10,
    date: "2026-03-23",
    paymentMethod: "Cash",
  },
  {
    id: "79",
    title: "Web Hosting",
    category: "Education",
    type: "expense",
    amount: 60,
    date: "2026-03-26",
    paymentMethod: "Card",
    note: "Annual plan",
  },
  {
    id: "80",
    title: "Freelance Bonus",
    category: "Freelance",
    type: "income",
    amount: 400,
    date: "2026-03-29",
    paymentMethod: "UPI",
    note: "Client tip",
  },
  {
    id: "81",
    title: "Swiggy Order",
    category: "Food",
    type: "expense",
    amount: 22,
    date: "2026-03-31",
    paymentMethod: "UPI",
  },

  // ── FEBRUARY 2026 (additional) ──────────────────────────────────────────────
  {
    id: "82",
    title: "Breakfast Cafe",
    category: "Food",
    type: "expense",
    amount: 15,
    date: "2026-02-03",
    paymentMethod: "Cash",
  },
  {
    id: "83",
    title: "Bus Pass",
    category: "Transport",
    type: "expense",
    amount: 30,
    date: "2026-02-05",
    paymentMethod: "Card",
  },
  {
    id: "84",
    title: "Investment Return",
    category: "Investment",
    type: "income",
    amount: 430,
    date: "2026-02-07",
    paymentMethod: "Bank Transfer",
  },
  {
    id: "85",
    title: "Haircut",
    category: "Other",
    type: "expense",
    amount: 15,
    date: "2026-02-08",
    paymentMethod: "Cash",
  },
  {
    id: "86",
    title: "Online Course",
    category: "Education",
    type: "expense",
    amount: 79,
    date: "2026-02-10",
    paymentMethod: "Card",
    note: "Node.js course",
  },
  {
    id: "87",
    title: "Movie Tickets",
    category: "Entertainment",
    type: "expense",
    amount: 28,
    date: "2026-02-12",
    paymentMethod: "Card",
    note: "2 tickets",
  },
  {
    id: "88",
    title: "Swiggy Order",
    category: "Food",
    type: "expense",
    amount: 26,
    date: "2026-02-17",
    paymentMethod: "UPI",
  },
  {
    id: "89",
    title: "Vitamin Supplements",
    category: "Health",
    type: "expense",
    amount: 32,
    date: "2026-02-19",
    paymentMethod: "Card",
  },
  {
    id: "90",
    title: "Cab Ride",
    category: "Transport",
    type: "expense",
    amount: 16,
    date: "2026-02-21",
    paymentMethod: "Card",
  },
  {
    id: "91",
    title: "Stationery",
    category: "Shopping",
    type: "expense",
    amount: 18,
    date: "2026-02-23",
    paymentMethod: "Cash",
  },
  {
    id: "92",
    title: "Water Bill",
    category: "Utilities",
    type: "expense",
    amount: 20,
    date: "2026-02-24",
    paymentMethod: "UPI",
  },
  {
    id: "93",
    title: "Snacks",
    category: "Food",
    type: "expense",
    amount: 12,
    date: "2026-02-28",
    paymentMethod: "Cash",
  },

  // ── JANUARY 2026 (additional) ───────────────────────────────────────────────
  {
    id: "94",
    title: "Parking Fee",
    category: "Transport",
    type: "expense",
    amount: 8,
    date: "2026-01-02",
    paymentMethod: "Cash",
  },
  {
    id: "95",
    title: "Swiggy Order",
    category: "Food",
    type: "expense",
    amount: 30,
    date: "2026-01-04",
    paymentMethod: "UPI",
  },
  {
    id: "96",
    title: "Water Bill",
    category: "Utilities",
    type: "expense",
    amount: 20,
    date: "2026-01-06",
    paymentMethod: "UPI",
  },
  {
    id: "97",
    title: "Investment Return",
    category: "Investment",
    type: "income",
    amount: 380,
    date: "2026-01-09",
    paymentMethod: "Bank Transfer",
  },
  {
    id: "98",
    title: "Haircut",
    category: "Other",
    type: "expense",
    amount: 15,
    date: "2026-01-11",
    paymentMethod: "Cash",
  },
  {
    id: "99",
    title: "Yoga Class",
    category: "Health",
    type: "expense",
    amount: 25,
    date: "2026-01-13",
    paymentMethod: "UPI",
  },
  {
    id: "100",
    title: "Cab Ride",
    category: "Transport",
    type: "expense",
    amount: 19,
    date: "2026-01-15",
    paymentMethod: "Card",
  },
  {
    id: "101",
    title: "Web Hosting",
    category: "Education",
    type: "expense",
    amount: 60,
    date: "2026-01-17",
    paymentMethod: "Card",
    note: "Domain renewal",
  },
  {
    id: "102",
    title: "Headphones Case",
    category: "Shopping",
    type: "expense",
    amount: 22,
    date: "2026-01-19",
    paymentMethod: "Card",
  },
];
